config/routes.rb
Rails.application.routes.draw do
  get 'chemicals/index'
  root :to => "crops#index"
  resources :fields, only: [:index, :show ]
  resources :crops, only: [ :index, :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chemical.rb
class Chemical < ApplicationRecord
  before_create :application_interval

  # convert weeks into days
  def application_interval
    self.application_frequency = self.application_frequency * 7
  end

  # determine price for chemical's next order
  def total_price(chemical, hectarage)
    hectarage * chemical.price_per_litre
  end
end

app/models/crop.rb
class Crop < ApplicationRecord
  # belongs_to :field
  has_many :chemicals

  def next_order(date, chemical)
    return (date + chemical.application_frequency) - 7
  end
end

app/models/farm.rb
class Farm < ApplicationRecord
  has_many :fields, dependent: :destroy
  has_many :crops, through: :fields, dependent: :destroy
end

app/models/field.rb
class Field < ApplicationRecord
  before_create :set_hectarage
  belongs_to :farm
  has_one :crop, class_name: "crop", foreign_key: "crop_id"

  private

  def set_hectarage
    self.hectarage = (self.length * self.width) / 10000
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  def index
    @crops = Crop.all
  end

  def show 
    @crop = Crop.find(params[:id])
    @fields = Field.where(crop_id: @crop.id)

    @hectarage = hectarage_count(@fields)
    @chemical = Chemical.find(@crop.chemical_id)
    @date = earliest_spray(@fields)
    @order_date = @crop.next_order(@date, @chemical)
  end

  private 
  # For each crop, find the earliest spray.
  def earliest_spray(fields)
    # Arbitrary date, in expanded programme this would be set to most recent order/delivery date
    date = Date.today
    fields.each do |field|
      field.last_sprayed < date ? date = field.last_sprayed : date
    end
    return date
  end

  # For each crop find the hectarage it covers
  def hectarage_count(fields)
    hectarage = 0
    fields.each do |field|
      hectarage += field.hectarage
    end
    return hectarage
  end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :find_field, only: [ :show, :edit, :update]

  def index
    @fields = Field.all
  end
    
  ##
  # EVERYTHING BELOW FOR CONTINUED PERSONAL DEVELOPMENT
  ##
  def show
    @crop = Crop.find(@field.crop_id)
    @chemical = Chemical.find(@crop.chemical_id)
    @offset = @chemical.application_frequency * 7
    @order_price = @chemical.price_per_litre * @field.hectarage
  end

  def edit
  end

  def update
  end

  private

  def find_field
    @field = Field.find(params[:id])
  end

  #prevent passing of malicious code into db
  def field_params
    params.require(:field).require(:name, :crop, :last_sprayed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chemicals_helper.rb
module ChemicalsHelper
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/crops/index.html.erb
<h1>Apple Tree Farm</h1>
<hr>
<% @crops.each do |crop| %>
  <h3>Crop: <%= crop.crop_name %></h3>
  <h3><%= Chemical.find(crop.chemical_id).name %></h3>
  <%= link_to crop.crop_name, crop_path(crop.id)  %>
<hr>
<% end %>

app/views/crops/show.html.erb
<h1>Apple Tree Farm</h1>
<hr>

  <h3>Crop: <%= @crop.crop_name %></h3>
  <h3><%= @chemical.name %></h3>
  <p>Next Order:</p>
  <ul>
    <li><p>Order Date: <%= @order_date %></p></li>
    <li><p>Order size: <%= @hectarage %> litres</p></li>
    <li><p>Order Price: £<%= @chemical.total_price(@chemical, @hectarage) %></p></li>
  </ul>
<hr>
<%= link_to "All crops", crops_path %>

app/views/fields/index.html.erb
<h1>Apple Tree Farm</h1>
<hr>
<% @fields.each do |field| %>
<h3><%= field.name %></h3>
<%= link_to "Field details", field_path(field)  %>
<hr>
<% end %>

app/views/fields/show.html.erb
<h1>Apple Tree Farm</h1>
<hr>
<h3><%= @field.name %></h3>
<p>Crop on Field: <%= @crop.crop_name %></p>
<p>Last Sprayed: <%= @field.last_sprayed %></p>
<p>Size: <%= @field.hectarage %></p>
<p>Chemical Used: <%= @chemical.name %></p>
<p>Next Spray: <%= @field.last_sprayed + @offset %></p>
<p>Next Order: </p> 
<ul>
  <li>Order Date: <%= @field.last_sprayed + @offset - 7 %></li>
  <li>Order Price: £<%= @order_price %> </li>
</ul>
<%= link_to "Back to fields", fields_path  %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CropCalculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>